# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.TextField()),
                ('accountNumber', models.TextField()),
                ('securityCode', models.TextField()),
                ('expiryDate', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.TextField()),
                ('password', models.TextField()),
                ('dateOfBirth', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DurationName', models.CharField(max_length=255)),
                ('NumOfDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SusuBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savingsAmount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('savingsDate', models.DateField()),
                ('lastRenewalDate', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='susuBoxWeb.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SusuHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLoginDate', models.DateField()),
                ('lastSavingsDate', models.DateField()),
                ('lastSavingsAmount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('successFul', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='susuBoxWeb.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='employmentStatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='susuBoxWeb.EmploymentStatus'),
        ),
        migrations.AddField(
            model_name='customer',
            name='genderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='susuBoxWeb.Gender'),
        ),
        migrations.AddField(
            model_name='account',
            name='typeOfCardId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='susuBoxWeb.TypeOfCard'),
        ),
    ]
