# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susuBoxWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
